easy_admin:
  site_name: 'Book Store'
  design:
    menu: [{ entity: 'Product', label: 'Books' }, { entity: 'ProductCategory', label: 'Book Categories' }]
  user:
    display_name: false
    display_avatar: false
  entities:
    # List the entity class name you want to manage

    Product:
      class: App\Entity\Product
      label: 'Book'
      list:
        actions: ['show']
        title: "Books"
        fields: ['id','name', 'description', 'price', 'quantity', { property: 'product_category.name', label: 'Category' }]
      form:
        fields: ['name', 'description', 'price', 'quantity',  { property: 'product_category', label: 'Book Category' } ]

    ProductCategory:
      class: App\Entity\ProductCategory
      label: 'Book Category'
      list:
        title: "Book Categories"
      form:
        fields: ['name']

